// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://avnrfhookjadabdhudtg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2bnJmaG9va2phZGFiZGh1ZHRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NTE1MjgsImV4cCI6MjA2MTIyNzUyOH0.skCiPfmbYpezj0RZn91ReFUGmZ1qLNBizdKTNBPObVQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);